<?php

namespace AppBundle\Repository;

/**
 * userTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userTestRepository extends \Doctrine\ORM\EntityRepository
{


}
