services:
#    tautof_platform.example:
#       class: tautof\PlatformBundle\Example
#       arguments: ["@service_id", "plain_value", "%parameter%"]

    app.photo1_uploader:
        class: tautof\PlatformBundle\FileUploader
        arguments: ['%photo1_directory%']
